### ISSUE TITLE
能否添加一个获取csgo资讯的功能

### ISSUE THREAD

**Issue by RIP-GitHub** [songsanggggg/csgoBot#3]

**Comment by songsanggggg** [comment]
我可以试一试抓一下完美的接口

**Comment by RIP-GitHub** [comment]
> 我可以试一试抓一下完美的接口

非常感谢

**Comment by RIP-GitHub** [comment]
> 我可以试一试抓一下完美的接口

我拿到了它的接口，https://appengine.wmpvp.com/steamcn/community/homepage/getHomeInformation?gameTypeStr=2&pageNum=1&pageSize=20
gameTypeStr为1时获取DOTA2资讯
gameTypeStr为2时获取CSGO资讯

**Comment by songsanggggg** [comment]
感谢，接口我收下了，我得研究一下，我最近计划重构一下，现在的就是屎山不堪入目哈哈哈

**Comment by songsanggggg** [comment]
写完了plugin-csgoNews.js
